version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: notruf-bot
    container_name: notruf-bot
    restart: on-failure
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      GUILD_ID: ${GUILD_ID}
      REPORT_CHANNEL_ID: ${REPORT_CHANNEL_ID}
      REPORT_CATEGORY_ID: ${REPORT_CATEGORY_ID}
      ENGLISH_ROLE_ID: ${ENGLISH_ROLE_ID}
      GERMAN_ROLE_ID: ${GERMAN_ROLE_ID}
